image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install bashbox
    before: curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall && exit
  - name: Compile bashbox project
    init: bashbox run --release
vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
