image:
  file: .gitpod.Dockerfile
tasks:
  - name: Run bashbox project
    command: bashbox run --release
vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
